sudo: true

language: go

go:
 - 1.6.x
 - 1.7.x
 - 1.8.x
 - master
matrix:
  fast_finish: true
  allow_failures:
    - go: master

env:
  global:
   - DISPLAY: ":99.0"

# Get coverage tools, and start the virtual framebuffer.
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y  gnuplot-x11

# Get deps, build, test, and ensure the code is gofmt'ed.
# If we are building as gonum, then we have access to the coveralls api key, so we can run coverage as well.
script:
 - go get -d -t -v ./...
 - go build -v ./...
 - go test -v ./...
 - test -z "$(gofmt -d .)"
 - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash ./.travis/test-coverage.sh; fi
